import LinkToDoc from "@/components/shared/link-to-doc";
import type { Metadata } from "next";

import { docs } from '@/utils';
export const metadata: Metadata = {
    title: "Documentation | Shadcn ui",
    description: "Generated by DEPO",
    icons: {
        icon: '/site/shadcn-dark.png'
    }
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const doc = docs[0]
    return (
        <>
            <div className='flex-1'>
                {/* <Button onClick={copylink}>Copy</Button> */}
                <div className="border-b">
                    <div className="container flex-1 items-start md:grid md:grid-cols-[220px_minmax(0,1fr)] md:gap-6 lg:grid-cols-[240px_minmax(0,1fr)] lg:gap-10">

                        <div className="fixed top-14 z-30 -ml-2 hidden h-[calc(100vh-3.5rem)] w-full shrink-0 md:sticky md:block">
                            <div className="relative overflow-hidden h-full py-6 pr-6 lg:py-8">
                                <div className="h-full w-full rounded-[inherit]">
                                    <div className="min-width: 100%; display: table;">
                                        <div className="w-full">
                                            <div className="relative overflow-hidden h-full flex-col flex items-start py-6 pr-6 lg:py-8 gap-5">
                                                <p className='font-bold'>
                                                    Getting Started
                                                </p>
                                                {docs.map(dc => (
                                                    <LinkToDoc title={dc.title} url={"docs/" + dc.url} />
                                                ))}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className='flex pt-10'>
                            <div className="mx-auto w-full min-w-0">
                                <div className="mb-4 flex items-center space-x-1 text-sm text-muted-foreground">
                                    <div className="overflow-hidden text-ellipsis whitespace-nowrap">Docs</div>
                                    <svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" className="h-4 w-4">
                                        <path d="M6.1584 3.13508C6.35985 2.94621 6.67627 2.95642 6.86514 3.15788L10.6151 7.15788C10.7954 7.3502 10.7954 7.64949 10.6151 7.84182L6.86514 11.8418C6.67627 12.0433 6.35985 12.0535 6.1584 11.8646C5.95694 11.6757 5.94673 11.3593 6.1356 11.1579L9.565 7.49985L6.1356 3.84182C5.94673 3.64036 5.95694 3.32394 6.1584 3.13508Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd">
                                        </path>
                                    </svg>
                                    <div className="font-medium text-foreground">{doc.title}</div>
                                </div>
                                <div className="space-y-2">
                                    <h1 className="scroll-m-20 text-4xl font-bold tracking-tight">Introduction</h1>
                                    <p className="text-lg text-muted-foreground">
                                        <span data-br=":r6a:" data-brr="1" style={{
                                            display: 'inline-block',
                                            verticalAlign: 'top',
                                            textDecoration: "inherit",
                                            maxWidth: '513px'
                                        }}></span>

                                    </p>
                                </div>
                                {children}
                            </div></div>
                    </div>
                </div>
            </div>
            {children}
        </>
    );
}
